global:
  registryOverride: "registry.redhat.io/rhacm2"
  imageOverrides:
    governance_policy_propagator: "governance-policy-propagator-rhel9@sha256:c82d38b3bd7f096e33149827a36c290a89476b1f73b38f52e2e674538edd359c"
    governance_policy_addon_controller: "acm-governance-policy-addon-controller-rhel9@sha256:694f26cec9556d5630333508e9e2ed9ce5fcf0172ec9691c3062ee787d1d004a"
    config_policy_controller: "config-policy-controller-rhel9@sha256:c8e7d879d10ef007ae2471335b07039198d207f5d574e4a7a1925988cb1d2b18"
    governance_policy_framework_addon: "acm-governance-policy-framework-addon-rhel9@sha256:dacc0d7a848e288e83b1091bad3765e64bbba5813d888c603f8aefcf8dfbf40f"
    klusterlet_addon_controller: "klusterlet-addon-controller-rhel9@sha256:035ae55c3c5b486b113424d510f5163ac558afa51c63bc4239a1ad4e2243d4d7"
  namespace: multicluster-engine
  pullSecret: open-cluster-management-image-pull-credentials
  cma:
    defaultConfig:
      name: addon-hosted-config
      namespace: multicluster-engine
