apiVersion: v2
appVersion: 2.11.4-529
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:589f6c602d2f3db5867f7a755668eaa3074d9dcb19ea0807e8e12048a607c09a
type: application
version: 2.11.4-529
